/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Animacion;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Reina
 */
public class Circulo extends javax.swing.JFrame {

    Point punto = new Point();
    int x, y;
    int fila;
    int i;
    float lleno1 = 145; //Altura de lleno termometro
    int inicio;

    /**
     * Creates new form Circulo
     */
    public Circulo() {
        initComponents();
        setSize(720, 500);
        setLocationRelativeTo(null);
        punto = lblPrueba.getLocation();
        //puntoLam = lblLmpara.getLocation();
        //punto2 = lblMedida.getLocation();
        x = (int) punto.getX();
        y = (int) punto.getY();
    }

    @Override
    public void paint(Graphics g) {
        if (inicio == 0) {
            super.paint(g);
            double c;
            fila = y + 185;
            for (int j = 0; j < 145; j++) {
                Color col = new Color(255, j / 3 + 9, j, 160);
                g.setColor(col);
//                    if (j < 40) {
//                        g.drawLine(x + 43 + j - 182, fila, x + 387 - j, fila);
//                    } else if (j < 80) {
//                        g.drawLine(x + 20, fila, x + 205, fila);
//                    } else 
//                if (j < 125) {
//                    g.drawLine(x + 43, fila, x + 43 + 35, fila);
//                } else 
                    if (j < lleno1) {
                    //g.drawLine(x + 43 + j -125, fila, x + 43 + 35 +125 - j, fila);
                    c = (double) (-1) * ((40 * 40) - (fila * fila));
                    System.out.println("c : " + c);
                    g.drawLine(x + 43 + (int) Math.sqrt(c) / 5 - 1, fila, x + 43 + 35 - (int) Math.sqrt(c) / 5 + 1, fila);
                } else {
                    System.out.println("Mal funcionamiento, se paso del limite");
                }
                pause(20);
                fila--;
            }
            inicio = (inicio + 1) % 2;
        }
//            Color col = new Color(255, 153, 153, 90);
//            g.setColor(col);
            g.fillOval (x+20, y+185, 80, 80);
//            //g.fillOval (x1+40, y1+40, 40, 150);
//            g.fillRoundRect(x1+43, y1+43, 35, 145, 35, 35);

    }

    public static void pause(long timeInMilliSeconds) {
        try {
            Thread.sleep(timeInMilliSeconds);

//        long timestamp = System.currentTimeMillis();
//
//        do {
//
//        } while (System.currentTimeMillis() < timestamp + timeInMilliSeconds);
        } catch (InterruptedException ex) {
            Logger.getLogger(frmTinaco.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrueba = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(lblPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Circulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Circulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Circulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Circulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Circulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPrueba;
    // End of variables declaration//GEN-END:variables
}
